### ISSUE TITLE
生成中の画像を逐次的に取得できるようにする

### ISSUE THREAD

**Issue by tebasakioisii** [IwamotoKakeru/gymlabo-hackathon#39]
1. `/api/generate` で画像生成を開始
2. `/api/get_image`でした画像を送る
    1. `/api/get_image`をする度に内部変数をインクリメントして送る画像を更新する
    2. count==MAXになるか、新たに`/api/generate`を送るとリセット

**Comment by srpkdyy** [comment]
PR
